### ISSUE TITLE
root folder

### ISSUE THREAD

**Issue by papapanyin** [balaramadurai/hugo-travelify-theme#1]
Still trying to find where the root folder is for me to copy the config.toml file and the data/l10n.toml

**Comment by balaramadurai** [comment]
Thank you for trying out my theme and raising this issue.

Please refer to http://gohugo.io/overview/quickstart/ and https://gohugo.io/overview/installing/ for installing Hugo and a theme. The root folder is where you find the folders - `content`, `data`, `static` and `themes`.

Thanks
Bala

**Comment by papapanyin** [comment]
Thanks
