### ISSUE TITLE
Menu entry begins with capitalization

### ISSUE THREAD

**Issue by ohobby** [balaramadurai/hugo-travelify-theme#10]
Hi,
Menu entry with multiple words, each word begins with capitalization.
This is not good.

thanks,
Oliver

**Comment by balaramadurai** [comment]
Hi Oliver,
  Thank you for this issue. 

I checked for documentation on Hugo. Unfortunately, Hugo formats the variable value to a capitalized form. If I force this to lower case, it can be difficult for other users. I am sorry, but I can't help with this one. 

I have asked the discussion forum about this - https://discourse.gohugo.io/t/issue-menu-entry-begins-with-capitalization/11828

Thanks and have a great day!
Bala

**Comment by pkollitsch** [comment]
`text-transform: lowercase;` on the menu link in CSS should do the trick.
