### ISSUE TITLE
nested menu sorted

### ISSUE THREAD

**Issue by Oliver2r** [balaramadurai/hugo-travelify-theme#11]
Hi,

nested menu normally sorted alphabetically.
Is it possible to determine for yourself how it should be sorted or in which order it should be displayed?

Thanks,
Oliver

**Comment by balaramadurai** [comment]
Hi Oliver,
  Thanks for your message. You can do it this way:

```
[[menu.main]]
    name  = "Contact2"
    url   = "/contact/"
    parent = "Contact"

[[menu.main]]
    name  = "Contact21"
    url   = "/contact/"
    parent = "Contact2"
    weight = 20

[[menu.main]]
    name  = "Contact22"
    url   = "/contact/"
    parent = "Contact2"
    weight = 10

[[menu.main]]
    name  = "Contact3"
    url   = "/contact/"
    parent = "Contact"
```

The `weight` can be used to use your own sort order.

Thanks
Bala
