### ISSUE TITLE
Slider Image link/url enabled

### ISSUE THREAD

**Issue by Oliver2r** [balaramadurai/hugo-travelify-theme#14]
Hi,
i like this https://github.com/balaramadurai/hugo-travelify-theme/issues/4 . Is it possible to make the slider image then link/url enabled that a klick to the image open the link/url. Like the function if the slider image comes from a post.
Possible place a variable "banner-url:" into the slider/2.yaml

Thanks,
Oliver

**Comment by balaramadurai** [comment]
Thanks Oliver for suggesting this. I have included "url:" in the yaml files. This is working now
