### ISSUE TITLE
Images on page 2 and more aren't showed 

### ISSUE THREAD

**Issue by LanaRyashchenko** [balaramadurai/hugo-travelify-theme#19]
Hi, Bala! Thank you for your job. 
Using your theme for my blog I faced a problem with images on page 2 and far. 
You can also see it by link: http://lanadays.com.s3-website-us-east-1.amazonaws.com/page/2/
Thank you for solving this problem and have a good day

**Comment by balaramadurai** [comment]
привет лана :smile: 
  Thanks for using this theme and for raising this issue. 

I checked your website. Looks like the banner is not showing the right path. Can you please make sure if the folder `banners` is inside the folder `static` and all your banner images are inside that folder?

If it is not the case, please let me know and I'll find out why this is happening.

Thanks and have a good day!
Bala

**Comment by balaramadurai** [comment]
Hi Lana,
  Thank you for your reply. Yes, you are right. It is indeed a bug in the second page. Added to that, the slider on the second page is also messed up because of the same reason. 

I've fixed them both. Please pull these changes.

Thanks again for your issue on this theme!

Please let me know if this solves your issue and then we can close this. Thanks!

Enjoy!
Bala

**Comment by LanaRyashchenko** [comment]
Hi, Bala!
I'm very appreciate your job and your help. I checked your changes and as a result issue with posts's images was solved. Images on page 2 are showed in a proper way. 
But images in slider still aren't seen. 
You can see this on my blog: http://lanadays.com.s3-website-us-east-1.amazonaws.com/page/2/
I'm thankful for your time and job.

Lana

**Comment by balaramadurai** [comment]
Hi Lana,
  There is an update to the code with the help of @darhon . 

Can you please let me know the settings you have set for the slider in the config file? 
Also, if you can see through your first set of posts (the ones on page 1) and let me know what the values of `banner` are in the posts, that will help me resolve this.

```
[params.slider]
    enable = true
    manual = false # Setting manual to true renders the slide selection to only those where the post has a slider=true option enabled
    num_features = 6 # The slider picks up the banner images from the N most recent posts, where num_features is N.
```

Thanks and have a great day!
Bala

**Comment by LanaRyashchenko** [comment]
Hi, Bala! 
I have asked @darhon to help me with this issue. He've made changes and now banner images work in a proper way. Please, check it yourself:
http://lanadays.com.s3-website-us-east-1.amazonaws.com/page/2/

I have the next values of banner:
[params.slider]
  enable          = true
  manual          = false
  num_features    = 5

Thank you for your time! 
Lana

**Comment by balaramadurai** [comment]
Excellent! Thanks @darhon for the help.

@LanaRyashchenko, your blog looks nice! You are very welcome! Glad you found the port of the travelify theme useful.

Cheers!
Bala
