### ISSUE TITLE
Page Speed Above the fold

### ISSUE THREAD

**Issue by Schokolader** [balaramadurai/hugo-travelify-theme#2]
It has the "above the fold" issue in google page speed: 
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fthemes.gohugo.io%2Ftheme%2Fhugo-travelify-theme%2F&tab=mobile

is it possible to solve this?

**Comment by balaramadurai** [comment]
Thanks @Schokolader for your interest in this theme. I have resolved the "above the fold" issue and also image optimization.

I don't know how to update the theme on the gohugo themes website. 

The demo http://balaramadurai.github.io and the theme https://balaramadurai/hugo-travelify-theme are updated. You can pull the latest theme from the github repo.

Thanks and have a great day!
Bala
