### ISSUE TITLE
Travelify Demo on Hugo website contains 3rd party tracking

### ISSUE THREAD

**Issue by onedrawingperday** [balaramadurai/hugo-travelify-theme#25]
Hello @balaramadurai 

I am one of the maintainers of the [Hugo Themes](https://github.com/gohugoio/hugoThemes/) repository.

Recently I audited the Hugo Themes website and it has [come to my attention](https://github.com/gohugoio/hugoThemes/issues/535) that your theme's demo has third party tracking enabled.

```
     \hugo-travelify-theme\exampleSite\config.toml:
        GoogleAnalytics = "UA-68204765-1"
```

To fix this issue please leave the above parameter blank i.e.

```
     \hugo-travelify-theme\exampleSite\config.toml:
        GoogleAnalytics = ""
```

Once you look into this please let me know.

Thank you!

**Comment by balaramadurai** [comment]
Hello @onedrawingperday 
  Thank you for raising this issue. Yes, this is definitely an oversight on my part. I have removed the dummy GA code from the code in this commit - ee1b269 

Please do let me know if this satisfies the need of the Hugo Themes website.

Thanks and have a great day!
Bala

**Comment by onedrawingperday** [comment]
@balaramadurai 

Thank you for the fix! 👍

**Comment by pidgeontower** [comment]
@onedrawingperday
Google Analytics removed as requested.
