### ISSUE TITLE
Logo in the title

### ISSUE THREAD

**Issue by enricodata** [balaramadurai/hugo-travelify-theme#27]
Hi,

Is it possible to add a logo in the title?
Like a logo instead of the word "Travelify"?

![image](https://user-images.githubusercontent.com/47527626/53289869-3da28e00-379c-11e9-88e1-a5227fc9a13e.png)

**Comment by balaramadurai** [comment]
Hello @enricodata ,
  Thank you for raising this issue. You can set the `logo_in_title` parameter to `false` if you want only the logo.

Please see if this change works for you.

Have a great day!
Bala

**Comment by enricodata** [comment]
Thank you. At the same time I found an alternative solution by modifying the html layout
