### ISSUE TITLE
mailchimpform

### ISSUE THREAD

**Issue by serragnoli** [balaramadurai/hugo-travelify-theme#29]
Nice template, thanks.

Can you tell me how how you generated this mailchimpform URL please? //balaramadurai.us15.list-manage.com/subscribe/post?u=7f4183fa2fe7abe3dc9f4efad&amp;id=49a3dd3745

The way I'm doing, it redirects to the form generated by MailChimp.

**Comment by balaramadurai** [comment]
Thank you @serragnoli for your github issue. I have updated the documentation to reflect what one needs to do to get the URL for the mailchimp. https://mailchimp.com/help/add-a-signup-form-to-your-website/
```
    # grab the mailchimpform value by following instructions here - https://mailchimp.com/help/add-a-signup-form-to-your-website/
    # Copy the URL in the action parameter inside the form
    # <div id="mc_embed_signup"><form action="https://balaramadurai.us15.list-manage.com/subscribe/post?u=7f4183fa2fe7abe3dc9f4efad&amp;id=49a3dd3745" method="post"
```
