### ISSUE TITLE
slider with extra posts and not with the recent posts

### ISSUE THREAD

**Issue by Oliver2r** [balaramadurai/hugo-travelify-theme#3]
Hi,

is it possible to configure special posts or sites for the slider and not to use the most recent posts?

Thanks,
Oliver

**Comment by balaramadurai** [comment]
Thanks @Oliver2r for your message.

Yes, now, you can do this with the parameter `manual` under `[[params.slider]]`

If you set `manual` to `true` in `config.toml` and in each of the posts that you want the banner to show up on the slider, set `slider=true` or `slider: true` in your frontmatter.

If you want the automatic feature back, you can set `manual` to be `false` and the slider will ignore the `slider` settings in each post.

Thanks again for your idea 😃 
Bala
