### ISSUE TITLE
Video in slide bar

### ISSUE THREAD

**Issue by dpotnuru75** [balaramadurai/hugo-travelify-theme#32]
Thanks for good work. 
I have a question, is there a way to include video or embed youtube video link in the slide bar in place of image.

**Comment by dpotnuru75** [comment]
Hi Bala, can you please help with this.

**Comment by balaramadurai** [comment]
Thanks @dpotnuru75 for bringing this up and sorry for not responding earlier.

I feel that this feature requires skills that are way above my paygrade... :) 

I'll give it a shot soon and see what I can do about this...

Thanks and have a nice day!
Bala

**Comment by balaramadurai** [comment]
Hi @dpotnuru75,
  Thank you for your wonderful idea to include videos in the slider.

I have added the video feature. Please do let me know if it works for you through 87d9cdf.

Thanks and have a wonderful new year!
Bala

**Comment by dpotnuru75** [comment]
Hi Bala,

Thanks for adding the video feature. Right now the slider is auto play. Can you please let me know to make it manual? because when the video is added to slider and played, the video's audio still palying in the background but the slider is moved to the next image. 

1. Its better to have the video silde untill the video is finished and then move to the next slide in case of auto functionality.
2. silder work only manually. 

Ideally option 1 is better.

Let me know how can we achieve this.

Regards,
Dev,
