### ISSUE TITLE
Issue with  Next Button

### ISSUE THREAD

**Issue by sree24** [balaramadurai/hugo-travelify-theme#36]
Hi @balaramadurai,

Apologies for opening another issue for this. As the other issue is closed I had no other option.
Need some help.
My base url is something like https://pages.github.com/companyname/sample-templates/ (this is just sample not exact url)
So for this when I click on Next button, its is going to https://pages.github.com/page/2 instead of https://pages.github.com/companyname/sample-templates/page/2.
I have verified that new page is available at correct location but Next button is not taking to that page.

Thanks,
Sree

**Comment by sree24** [comment]
Found a resolution for this issue. Closing it.

**Comment by balaramadurai** [comment]
Hi @sree24,
  I am very happy that you resolved this issue on your own. Thank you for informing me about it.

Can you please let me know what settings you changed to get this working for you? Maybe it will help others who may have such problems in the future.

Thanks
Bala

**Comment by sree24** [comment]
Sure. I edited the paginationtion.html in layouts> partials folder.
Removed the absURL for Previous and Next
**<a class="extend prev" rel="prev" href="{{ .Paginator.Prev.URL }}">**

**Comment by balaramadurai** [comment]
@sree24, Thanks a lot for your help. I have made that change in the theme itself.

Bala
