### ISSUE TITLE
suggestion Slider with image and text but not from a post

### ISSUE THREAD

**Issue by Oliver2r** [balaramadurai/hugo-travelify-theme#4]
Hi, 
possible a new idea/suggestion.
Slider with image and text but not from a post. (Able with internal or external link or without link)
It would be nice to take pictures with more or less text and link or no link in the sider without having a post for it.
regards,
Oliver

**Comment by balaramadurai** [comment]
This is DONE. I have left instructions in the README

Thanks for this idea as well! 👍 😄
