### ISSUE TITLE
Sharebutton Email

### ISSUE THREAD

**Issue by Oliver2r** [balaramadurai/hugo-travelify-theme#7]
Hi,

at the share buttons i missing a email share button.

Like https://schier.co/blog/2014/10/22/pure-html-share-buttons.html or like this https://github.com/heiseonline/shariff

Thanks,
Oliver

**Comment by balaramadurai** [comment]
Thanks again @Oliver2r for doing the basic research for me. Now I understand.

I have added the Email share button as well. You can use the `l10n.toml` in the `data` folder now to customize the wordings in the email draft.

Thanks and have a great day!
Bala
